### PR TITLE
sort votes and add links for each person in votes tab

### PR DESCRIPTION
**Pull request by tohuynh**
Issues 14 and 15.
Sort the decision items base on index so that they appear in the same order as minutes in details.
Add links to each person.
Sort persons alphabetically.
Remove table headers on smaller screens

### CODE REVIEW

**Comment by tohuynh** [comment]
Issue 19
Replace event link icon with body name and event datetime.
Sort votes according to datetime, and then index, both in descending order so that the person's most recent decision appears first.

**Comment by evamaxfield** [comment]
Thanks for your PR!

**Relevant issues:**
* Resolves #14 
   * [Staging Example](https://jacksonmaxfield.github.io/cdp-frontend-dev/#/events/206533e7-1d87-44da-932b-51210cf1e78e)
   * Notes: Go to votes tab

* Resolves #15 
   * [Staging Example](https://jacksonmaxfield.github.io/cdp-frontend-dev/#/events/206533e7-1d87-44da-932b-51210cf1e78e)
   * Notes: Go to votes tab


* Resolves #19 
   * [Staging Example](https://jacksonmaxfield.github.io/cdp-frontend-dev/#/people/e41e92c1-a7f9-4fa3-b37e-788d72bbfca1)
   * Notes: n/a

**Notes to other reviewers:**
n/a

**Review by evamaxfield — APPROVED** [review]
Thanks again for your contribution! This looks great and I am going to approve and merge. Do you have any ideas as to how well the current system will work with #18?

**Comment by evamaxfield** [comment]
Also as general feedback, this is not an issue for now, but in the future, it may be useful to revisit how sorting is currently being done client side. GH #24 and the related branch has new database interaction functions that allow for sorting on server side which should reduce render times.

**Pull request merged**
